### ISSUE TITLE
TestNG-Foundation 1.13.3 not working with last TestNG version 7.1.0

### ISSUE THREAD

**Issue by Zahorodnii** [Nordstrom/TestNG-Foundation#37]
Can't find IAnnotationTransformer3

**Comment by sbabcoc** [comment]
Due to unresolved issues with notifications, I never upgraded beyond TestNG 6.10

I'll need to see how this more recent version behaves, and see what can be done to address the issue reported here.

**Comment by sbabcoc** [comment]
@Zahorodnii The latest release (2.0.0) upgrades to TestNG 7.1.0, which is what you were looking for. Let me know how this works for you.

**Comment by Zahorodnii** [comment]
[Maven](https://mvnrepository.com/artifact/com.nordstrom.tools/testng-foundation) still not update version

**Comment by sbabcoc** [comment]
Odd that the new release hasn't propagated yet. You can get it now from [here](https://repo1.maven.org/maven2/com/nordstrom/tools/testng-foundation/2.0.0/).

**Comment by sbabcoc** [comment]
The release finally showed up on the instance of Maven Central you pointed to.
