### ISSUE TITLE
Provide usage example for ExecutionFlowController

### ISSUE THREAD

**Issue by yaroslav-orel** [Nordstrom/TestNG-Foundation#6]
Could you please provide use cases for ExecutionFlowController? Can't figure out how to benefit from this feature.

**Comment by sbabcoc** [comment]
[HappyPathClass](https://github.com/Nordstrom/TestNG-Foundation/blob/master/src/test/java/com/nordstrom/automation/testng/HappyPathClass.java) provides a really basic example of the attribute hand-off provided by **ExecutionFlowController**. This feature is utilized by [Selenium Foundation](https://github.com/Nordstrom/Selenium-Foundation) to automatically propagate driver session and initial page objects from `before` configuration to test method to `after` configuration. Without this support, such propagation is a messy, roll-your-own affair.

**Comment by yaroslav-orel** [comment]
@sbabcoc unfortunately this still isn't clear for me. What would be different without ExecutionFlowController applied to HappyPathClass?

**Comment by da-yaroslav-orel** [comment]
Okay. Thanks for the explanation

**Comment by sbabcoc** [comment]
I copied this explanation to the Wiki for future reference.
